/* ===== 소원 미션 카드 (미션 화면, 매일 미션과 별도) ===== */
function wishRefresh(){if(document.getElementById("boxModal"))openWish();wmRender()}
function wmRender(){const e=document.getElementById("wmCard");if(!e)return;const adult=me!=="아이",td=dsn(),act=wish.filter(w=>w.st===""&&w.m),wait=wish.filter(w=>w.st==="new"),req=wish.filter(w=>w.st==="req");
 if(!adult&&!act.length&&!req.length){e.innerHTML="";return}
 e.innerHTML=`<div class="fcc"><div class="spt">🎁 소원 미션 <small>매일 미션과는 따로예요</small></div>`+(adult&&!act.length&&!req.length&&!wait.length?'<div class="fcnote">아이가 해냈을 때 선물을 줄 "소원 미션"을 따로 만들 수 있어요. 오늘의 스탬프 미션과는 관계없어요.</div>':"")+
 act.map(w=>{const p=w.p||0,t=w.t||1,pc=Math.round(p/t*100);return `<div style="margin:8px 0"><div style="font-weight:900;font-size:15px">🎁 ${esc(w.n)}</div><div style="font-size:14px;margin:2px 0">🎯 ${esc(w.m)} · ${p}/${t}일</div><div style="height:8px;background:#eadcf0;border-radius:6px;overflow:hidden"><div style="width:${pc}%;height:100%;background:#745cff"></div></div>${w.l===td?'<div style="margin-top:6px;font-weight:900;color:#2e9e57">✅ 오늘 했어요!</div>':`<div class="spbtn"><button onclick="wishTick(${w.id})">✅ 오늘 했어요!</button></div>`}${adult?`<div class="spbtn"><button class="alt" onclick="wishNow(${w.id})">🎁 지금 허락하기</button></div>`:""}</div>`}).join("")+
 req.map(w=>`<div style="margin:8px 0;font-weight:900">🎉 ${esc(w.n)} — 미션 성공! ${adult?'<button onclick="wishDone('+w.id+');wishRefresh()" style="margin-left:6px;border:0;background:#745cff;color:#fff;border-radius:10px;padding:6px 10px;font-weight:900">✅ 허락했어요</button>':"부모님 확인 중"}</div>`).join("")+
 (adult?'<div class="spbtn"><button onclick="wishMakeOpen()">➕ 소원 미션 만들기</button></div>':"")+(adult?wait.map(w=>`<div style="margin:8px 0;font-weight:900">✏️ ${esc(w.n)} — 미션을 정해 주세요 <button onclick="wishMissionOpen(${w.id})" style="margin-left:6px;border:0;background:#ff72a4;color:#fff;border-radius:10px;padding:6px 10px;font-weight:900">🎯 미션 정하기</button></div>`).join(""):"")+`</div>`}

function wishMakeOpen(){wmD=7;const ms=["📚 책 읽기","🧹 방 정리하기","🪥 스스로 양치하기","📝 숙제 먼저 하기","🙏 가족 도와주기","😴 일찍 자기","🍚 밥 남기지 않기","🏃 운동하기"],gs=["🎬 영화 보기","🍦 아이스크림","🛝 놀이터 1시간","📚 책 사기","🍕 맛있는 외식","🧸 인형 사기"];
 boxOpen(`<h2>➕ 소원 미션 만들기</h2><small style="color:#83778b">미션을 해내면 선물을 주는 약속이에요. 매일 스탬프 미션과는 따로예요.</small><div style="font-weight:900;margin-top:8px">🎁 선물</div><div class="whochips" style="margin:6px 0">${gs.map(x=>`<button onclick="wiMg.value='${x}'">${x}</button>`).join("")}</div><input id="wiMg" maxlength="24" placeholder="선물 (직접 써도 돼요)" style="width:100%;border:2px solid #eadcf0;border-radius:12px;padding:9px;font-size:15px"><div style="font-weight:900;margin-top:10px">🎯 미션</div><div class="whochips" style="margin:6px 0">${ms.map(x=>`<button onclick="wiMt.value='${x}'">${x}</button>`).join("")}</div><input id="wiMt" maxlength="24" placeholder="직접 써도 돼요" style="width:100%;border:2px solid #eadcf0;border-radius:12px;padding:9px;font-size:15px"><div style="font-weight:900;margin-top:10px">며칠 동안? <span id="wmDv" style="color:#745cff">7일</span></div><div class="whochips" style="margin:6px 0">${[1,3,5,7,10,14,21,30].map(d=>`<button onclick="wmD=${d};wmDv.textContent='${d}일'">${d}일</button>`).join("")}</div><button class="ok" onclick="wishMake()">✅ 만들었어요</button>`)}
function wishMake(){const g=(document.getElementById("wiMg").value||"").trim(),m=(document.getElementById("wiMt").value||"").trim();if(!g||!m){alert("선물과 미션을 모두 정해 주세요");return}wish.push({id:nid(),n:g,m:m,t:wmD,p:0,l:"",st:"",by:me||""});svWi();closeBox();wmRender();try{render()}catch(e){}}

/* ===== 일정 화면은 항상 오늘 날짜로 시작 (앱을 켜 둔 채 날짜가 바뀌거나 다시 돌아왔을 때) ===== */
var _lastD=dsn();
function dayRoll(back){const d=dsn(),ch=d!==_lastD;if(ch){_lastD=d;try{dailyAuto(false);afterAuto()}catch(e){}}if(ch||back){try{const t=new Date();evY=t.getFullYear();evM=t.getMonth();evSel=d}catch(e){}try{renderEv();render()}catch(e){}}}
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")dayRoll(true)});
setInterval(()=>dayRoll(false),60000);

/* ===== 다른 날짜를 보고 있어도 맨 위에 오늘 일정을 고정해서 보여 줘요 ===== */
function pinToday(){const t=new Date(),k=ds(t),E=dayEvents(k).filter(x=>!x.mis).sort((a,b)=>(a.t||"").localeCompare(b.t||""));
 return `<div class="evday" style="background:#fff7e8;border-color:#ffb8d2;margin:0 0 8px"><h3 onclick="evToday()" style="cursor:pointer">📌 오늘 ${t.getMonth()+1}월 ${t.getDate()}일 (${WDN[t.getDay()]}) <small style="color:#745cff;font-size:12px">${E.length?E.length+"개 · ":""}눌러서 오늘로 ▶</small></h3>`+
 (E.length?E.slice(0,4).map(x=>`<div class="hrow${x.ok?" ok":""}"><span class="evt">${x.msg?"💌":(x.t?rngH(x.t,x.te):"종일")}</span><div><b>${esc(x.n)}</b></div></div>`).join("")+(E.length>4?`<div class="hsub">외 ${E.length-4}개</div>`:""):'<div class="evempty" style="padding:6px">오늘은 등록된 일정이 없어요</div>')+`</div>`}
async function updCheck(){const b=document.getElementById("updBtn"),t=document.getElementById("buildTag");const say=m=>{if(b)b.textContent=m;else alert(m)};say("확인 중… ⏳");
 try{const r=await fetch("/?chk="+Date.now(),{cache:"no-store"});const h=await r.text();const m=h.match(/const APP_BUILD="([^"]+)"/);
  if(m&&m[1]===APP_BUILD){say("✅ 최신 버전이에요 ("+APP_BUILD+")");setTimeout(()=>{if(b)b.textContent="🔄 업데이트 확인하기"},3000);return}
  say("🆕 새 버전을 적용하는 중…");try{const rs=await navigator.serviceWorker.getRegistrations();rs.forEach(x=>x.update())}catch(e){}try{const ks=await caches.keys();await Promise.all(ks.map(k=>caches.delete(k)))}catch(e){}
  setTimeout(()=>location.replace("/?u="+Date.now()),400)}catch(e){say("⚠️ 인터넷을 확인해 주세요")}}
function buildTag(){const t=document.getElementById("buildTag");if(t)t.textContent="🕒 마지막 업데이트 "+APP_BUILD}
buildTag();ensurePending();renderFriends();render();introInit();buddyFace.onclick=()=>{const fid=earned&&earned.day===dsn()?earned.f:(partnerF()>=0?partnerF():pending);tapK++;react(buddyFace,fid,null,actFor(fid,nDone()-1+tapK))};tick();setInterval(tick,15000);setInterval(askMe,2500);setInterval(evAlarmTick,20000);setInterval(()=>fetchMsgs(false),10000);setTimeout(()=>{fetchMsgs(false);updMsgDot()},1800);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")fetchMsgs(true)});document.getElementById("cInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.isComposing){e.preventDefault();sendMsg()}});setTimeout(evAlarmTick,2500);setTimeout(()=>{ensurePush(false).then(x=>{pushState=x;updPushStat()}).catch(()=>{});pushSync(true)},3000);setInterval(pushSync,30000);if(navigator.serviceWorker){navigator.serviceWorker.addEventListener("message",e=>{if(e.data&&e.data.go)goTab(e.data.go==="c"?"c":e.data.go==="e"?"e":"m")});const g=new URLSearchParams(location.search).get("go");if(g)setTimeout(()=>goTab(g==="c"?"c":g==="e"?"e":"m"),1500)}updPushStat();
