/* ---- 가족 공유 (Supabase) ---- */
const SB_URL="https://ayygbemcxuajccaknfir.supabase.co",SB_KEY="sb_publishable_tiLGpJNheNZZ4Yn9cIhTow_HjW2dx2E";
const SBOK=/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(SB_URL)&&SB_KEY.length>30&&!/YOUR/.test(SB_KEY+SB_URL);
const SYNCK=["Tasks","Done","MT","MP","Reward","Goal","Total","Streak","Day","Owned","Pending","Earned","Names","Pre","PreDone","Coins","CT","Care","Partner","Quiz","QStat","Pin","Week","Skip","Auto","Ev","Cal","Shop","Wish","Pstk","Sp","Fc","Fun","Gone","Fset"];
let fam="",syncTs=0,pushT=null,busyP=false,busyL=false;
try{fam=localStorage.getItem("mobileKongFam")||"";syncTs=+(localStorage.getItem("mobileKongSyncTs")||0)}catch(e){}
const TE=new TextEncoder(),TD=new TextDecoder(),keyCache={};
const b64=u=>{let t="";new Uint8Array(u).forEach(c=>t+=String.fromCharCode(c));return btoa(t)},unb64=t=>Uint8Array.from(atob(t),c=>c.charCodeAt(0));
async function idOf(code){const h=await crypto.subtle.digest("SHA-256",TE.encode("kk-id:"+code));return Array.from(new Uint8Array(h),x=>x.toString(16).padStart(2,"0")).join("")}
function keyOf(code){return keyCache[code]||(keyCache[code]=crypto.subtle.importKey("raw",TE.encode(code),"PBKDF2",false,["deriveKey"]).then(m=>crypto.subtle.deriveKey({name:"PBKDF2",salt:TE.encode("kongkong-mission-v1"),iterations:100000,hash:"SHA-256"},m,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])))}
async function encObj(code,obj){const iv=crypto.getRandomValues(new Uint8Array(12)),k=await keyOf(code),ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,TE.encode(JSON.stringify(obj))),o=new Uint8Array(12+ct.byteLength);o.set(iv);o.set(new Uint8Array(ct),12);return{v:1,e:b64(o)}}
async function decObj(code,w){const raw=unb64(w.e),k=await keyOf(code),pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:raw.slice(0,12)},k,raw.slice(12));return JSON.parse(TD.decode(pt))}
async function rpc(fn,args){const h={"Content-Type":"application/json",apikey:SB_KEY};if(/^eyJ/.test(SB_KEY))h.Authorization="Bearer "+SB_KEY;const r=await fetch(SB_URL+"/rest/v1/rpc/"+fn,{method:"POST",headers:h,body:JSON.stringify(args)});if(!r.ok)throw new Error(r.status);const t=await r.text();return t?JSON.parse(t):null}
function famMsg(t){const e=document.getElementById("famMsg");if(e)e.textContent=t}
function schedulePush(){if(!fam||!SBOK)return;clearTimeout(pushT);pushT=setTimeout(pushNow,1200)}
async function pushNow(){if(!fam||!SBOK||busyP)return;busyP=true;pushT=null;try{const data={};SYNCK.forEach(k=>{const v=localStorage.getItem("mobileKong"+k);if(v!==null)data[k]=v});const ts=Math.max(Date.now(),syncTs+1);await rpc("kong_put",{p_code:await idOf(fam),p_data:await encObj(fam,data),p_ts:ts});syncTs=ts;localStorage.setItem("mobileKongSyncTs",String(ts));famMsg("✅ 동기화됨 "+new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}))}catch(e){famMsg("⚠️ 서버에 연결하지 못했어요. 잠시 후 다시 시도해요");pushT=setTimeout(pushNow,20000)}busyP=false}
function applyRemote(r){SYNCK.forEach(k=>{const v=r.data&&r.data[k];if(v===undefined||v===null)localStorage.removeItem("mobileKong"+k);else localStorage.setItem("mobileKong"+k,v)});localStorage.setItem("mobileKongSyncTs",String(r.ts));location.reload()}
async function pull(){if(!fam||!SBOK||busyL||pushT||busyP)return;busyL=true;try{const r=await rpc("kong_get",{p_code:await idOf(fam)});if(r&&r.ts>syncTs){if(document.querySelector(".modal.show")||document.getElementById("intro")){busyL=false;return}applyRemote({data:await decObj(fam,r.data),ts:r.ts});return}if(r)famMsg("✅ 최신 상태예요")}catch(e){}busyL=false}
function syncNow(){famMsg("동기화 중…");pushT&&clearTimeout(pushT);(async()=>{await pull();if(!busyL)await pushNow()})()}
function genCode(){const a="abcdefghjkmnpqrstuvwxyz23456789",b=new Uint8Array(20);crypto.getRandomValues(b);return Array.from(b,x=>a[x%a.length]).join("")}
function famUI(){famOff.style.display=!SBOK?"":"none";famNew.style.display=(SBOK&&!fam)?"":"none";famOn.style.display=(SBOK&&fam)?"":"none";famShowOff()}
var famTm=0;function famShowOff(){clearTimeout(famTm);famCode.textContent=fam?"●".repeat(fam.length>20?20:fam.length):"";famCode.dataset.on="";const e=document.getElementById("famEye");if(e)e.textContent="👁 보기"}
function toggleFamCode(){if(famCode.dataset.on){famShowOff();return}if(!pinHash){alert("먼저 아래 🔒 비밀번호에서 숫자 4자리를 정해 주세요.\n정하지 않으면 아이가 설정에 들어와서 코드를 볼 수 있어요.");return}famCode.textContent=fam;famCode.dataset.on="1";document.getElementById("famEye").textContent="🙈 숨기기";clearTimeout(famTm);famTm=setTimeout(famShowOff,8000)}
async function createFam(){if(!SBOK)return;fam=genCode();localStorage.setItem("mobileKongFam",fam);await pushNow();if(syncTs===0){fam="";localStorage.removeItem("mobileKongFam");famUI();alert("서버에 연결하지 못했어요. 인터넷을 확인해 주세요");return}famUI();alert("가족 코드를 만들었어요! 초대 링크를 가족에게 보내 주세요");if(!pinHash){const v=prompt("아이가 설정을 열지 못하게 잠글 비밀번호 숫자 4자리를 정해 주세요.\n(취소하면 나중에 설정의 🔒 비밀번호에서 정할 수 있어요)");if(v&&/^\d{4}$/.test(v.trim())){pinHash=hp(v.trim());try{localStorage.setItem("mobileKongPin",pinHash)}catch(e){}schedulePush();render();alert("설정 비밀번호를 저장했어요")}}}
async function joinCode(code){code=(code||"").trim().toLowerCase();{const m=code.match(/code=([a-z0-9]+)/);if(m)code=m[1]}if(code.length<16){alert("가족 코드를 정확히 입력해 주세요");return}try{const r=await rpc("kong_get",{p_code:await idOf(code)});if(!r){alert("없는 코드예요. 다시 확인해 주세요");return}const data=await decObj(code,r.data);if(!confirm("이 폰의 기록이 가족 기록으로 바뀌어요. 연결할까요?"))return;fam=code;localStorage.setItem("mobileKongFam",fam);applyRemote({data,ts:r.ts})}catch(e){alert("서버에 연결하지 못했어요")}}
function joinFam(){joinCode(famInput.value)}
function leaveFam(){if(!confirm("이 폰의 가족 연결을 끊을까요?\n기록은 이 폰에 그대로 남아요."))return;fam="";syncTs=0;localStorage.removeItem("mobileKongFam");localStorage.removeItem("mobileKongSyncTs");famUI()}
function famLink(){return location.origin+location.pathname+"#code="+fam}
async function shareFam(){const u=famLink();try{if(navigator.share){await navigator.share({title:"콩콩 미션",text:"콩콩 미션 가족 초대예요! 링크를 열면 같은 기록을 볼 수 있어요.",url:u});return}}catch(e){if(e&&e.name==="AbortError")return}try{await navigator.clipboard.writeText(u);alert("초대 링크를 복사했어요! 카톡에 붙여넣어 보내 주세요")}catch(e){prompt("이 링크를 복사해서 보내 주세요",u)}}
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")pull()});setInterval(pull,15000);
(function(){if(SBOK&&!fam&&/^#code=/.test(location.hash)){const c=location.hash.slice(6);history.replaceState(null,"",location.pathname);setTimeout(()=>{if(confirm("가족 코드로 연결할까요?\n이 폰의 기록이 가족 기록으로 바뀌어요."))joinCode(c)},900)}else if(location.hash.startsWith("#code="))history.replaceState(null,"",location.pathname)})();
const rnd=n=>Math.floor(Math.random()*n),pickOne=a=>a[rnd(a.length)],shufA=a=>a.map(x=>[Math.random(),x]).sort((p,q)=>p[0]-q[0]).map(x=>x[1]);
function numOpts(ans,steps){const st=new Set([ans]);let g=0;while(st.size<3&&g++<80){const v=ans+pickOne(steps)*(Math.random()<.5?-1:1);if(v>=0)st.add(v)}let k=1;while(st.size<3)st.add(ans+k++);return shufA([...st]).map(v=>({t:String(v),ok:v===ans}))}
function txtOpts(ans,wr){return shufA([ans,...shufA(wr.filter(x=>x!==ans)).slice(0,2)]).map(t=>({t,ok:t===ans}))}
const EN=[["🍎","apple","사과"],["🍌","banana","바나나"],["🍇","grape","포도"],["🍓","strawberry","딸기"],["🍊","orange","오렌지"],["🍉","watermelon","수박"],["🐶","dog","강아지"],["🐱","cat","고양이"],["🐰","rabbit","토끼"],["🐻","bear","곰"],["🐘","elephant","코끼리"],["🐟","fish","물고기"],["🐦","bird","새"],["🐷","pig","돼지"],["🐮","cow","소"],["🐵","monkey","원숭이"],["🦁","lion","사자"],["🐢","turtle","거북이"],["☀️","sun","해"],["🌙","moon","달"],["⭐","star","별"],["🌈","rainbow","무지개"],["🌸","flower","꽃"],["🌳","tree","나무"],["🚗","car","자동차"],["🚌","bus","버스"],["✈️","airplane","비행기"],["🏠","house","집"],["📚","book","책"],["✏️","pencil","연필"],["⚽","ball","공"],["🎂","cake","케이크"],["🥛","milk","우유"],["💧","water","물"],["🍚","rice","밥"],["🍞","bread","빵"],["👁️","eye","눈"],["👃","nose","코"],["👂","ear","귀"],["🖐️","hand","손"]];
const EN2=[["red","빨강"],["blue","파랑"],["yellow","노랑"],["green","초록"],["pink","분홍"],["white","하양"],["black","검정"],["one","1"],["two","2"],["three","3"],["four","4"],["five","5"],["six","6"],["seven","7"],["eight","8"],["nine","9"],["ten","10"],["Hello","안녕하세요"],["Thank you","고마워요"],["Sorry","미안해요"],["Good morning","좋은 아침"],["Good night","잘 자요"],["Yes","네"],["No","아니요"]];
const PH=[["What's your name?","이름이 뭐예요?","My name is Sam.",["I'm fine, thank you.","I'm eight."]],["How are you?","잘 지내요?","I'm fine, thank you.",["My name is Sam.","It's a dog."]],["How old are you?","몇 살이에요?","I'm eight.",["It's red.","I'm fine, thank you."]],["What's this?","이게 뭐예요?","It's an apple.",["I'm eight.","Yes, I am."]],["What color is it?","무슨 색이에요?","It's red.",["I'm eight.","My name is Sam."]],["Nice to meet you.","만나서 반가워요.","Nice to meet you, too.",["I'm eight.","It's a cat."]],["Thank you.","고마워요.","You're welcome.",["Good night.","I'm eight."]],["I'm sorry.","미안해요.","That's okay.",["Good morning.","It's red."]],["Good morning.","좋은 아침이에요.","Good morning!",["My name is Sam.","It's a dog."]],["Good night.","잘 자요.","Good night!",["You're welcome.","It's red."]],["Goodbye.","잘 가요.","Bye!",["Good morning!","I'm eight."]],["Do you like apples?","사과 좋아해요?","Yes, I do.",["My name is Sam.","It's red."]],["Are you happy?","행복해요?","Yes, I am.",["It's a dog.","My name is Sam."]],["Can you swim?","수영할 수 있어요?","Yes, I can.",["It's an apple.","I'm eight."]],["What do you like?","무엇을 좋아해요?","I like pizza.",["I'm fine, thank you.","You're welcome."]],["Hello!","안녕하세요!","Hello!",["Goodbye.","It's red."]]];
const GEN=[["무지개는 몇 가지 색일까?","7가지",["3가지","5가지"]],["하루는 몇 시간일까?","24시간",["12시간","60시간"]],["일주일은 며칠일까?","7일",["5일","10일"]],["1년은 몇 달일까?","12달",["10달","24달"]],["우리나라의 수도는?","서울",["부산","대구"]],["우리나라 국기의 이름은?","태극기",["일장기","성조기"]],["거미의 다리는 몇 개일까?","8개",["4개","6개"]],["개미의 다리는 몇 개일까?","6개",["4개","8개"]],["다음 중 바다에 사는 동물은?","상어",["호랑이","토끼"]],["해는 어느 쪽에서 뜰까?","동쪽",["서쪽","남쪽"]],["눈이 펑펑 오는 계절은?","겨울",["여름","봄"]],["신호등이 초록불이면?","건너요",["멈춰요","뛰어요"]],["불이 났을 때 걸어야 하는 번호는?","119",["112","114"]],["위험할 때 경찰 아저씨를 부르는 번호는?","112",["119","114"]],["꿀을 만드는 곤충은?","벌",["나비","모기"]],["올챙이가 자라면 무엇이 될까?","개구리",["물고기","거북이"]],["물이 꽁꽁 얼면 무엇이 될까?","얼음",["구름","비"]],["우리 눈은 모두 몇 개일까?","2개",["1개","3개"]],["식물이 자라려면 필요한 것은?","햇빛과 물",["장난감","사탕"]],["다음 중 가장 큰 동물은?","고래",["코끼리","기린"]],["봄 다음에 오는 계절은?","여름",["겨울","가을"]],["월요일 다음 날은?","화요일",["일요일","수요일"]],["삼각형의 변은 몇 개일까?","3개",["4개","5개"]],["사각형의 꼭짓점은 몇 개일까?","4개",["3개","5개"]],["한 손에 손가락은 몇 개일까?","5개",["4개","6개"]],["빨강과 노랑을 섞으면?","주황",["초록","보라"]],["파랑과 노랑을 섞으면?","초록",["주황","분홍"]],["야옹야옹 우는 동물은?","고양이",["강아지","소"]],["우유는 어떤 동물에게서 얻을까?","소",["닭","돼지"]],["하늘을 날 수 있는 동물은?","새",["물고기","거북이"]],["밤하늘에 반짝반짝 빛나는 것은?","별",["구름","무지개"]],["사과는 어떤 종류일까?","과일",["채소","동물"]],["비 오는 날 쓰는 것은?","우산",["선글라스","수영복"]],["양치질은 하루에 몇 번 하면 좋을까?","3번",["0번","10번"]],["손을 깨끗이 씻을 때 쓰는 것은?","비누",["모래","풀"]]];
let recentQ=[],curQ=null,qTry=0;
function genQ(){const kinds=[];if(qz.mul&&qz.tb.length)kinds.push("mul");if(qz.add&&(qz.ls||qz.lt))kinds.push("add");if(qz.eng)kinds.push("eng");if(qz.gen)kinds.push("gen");if(!kinds.length)return null;
 const k=pickOne(kinds);
 if(k==="mul"){const a=pickOne(qz.tb),b=1+rnd(9),ans=a*b;return{tag:"✖️ 곱셈",q:a+" × "+b+" = ?",sub:"",opts:numOpts(ans,[a,1,2,a+1].filter(x=>x>0))}}
 if(k==="add"){const lv=[];if(qz.ls)lv.push("s");if(qz.lt)lv.push("t","u");const L=pickOne(lv);let a,b,op=Math.random()<.5?"+":"−",ans;
  if(L==="s"){if(op==="+"){a=1+rnd(12);b=1+rnd(Math.min(9,20-a));ans=a+b}else{a=5+rnd(16);b=1+rnd(Math.min(9,a-1));ans=a-b}}
  else if(L==="t"){if(op==="+"){a=(1+rnd(7))*10;b=(1+rnd(Math.min(9-a/10,8)))*10;ans=a+b}else{a=(2+rnd(8))*10;b=(1+rnd(a/10-1))*10;ans=a-b}}
  else{if(op==="+"){const x=1+rnd(6),y=1+rnd(8-x+1),u=rnd(8),v=rnd(9-u);a=x*10+u;b=y*10+v;ans=a+b}else{const x=2+rnd(7),y=rnd(x),u=1+rnd(9),v=rnd(u+1);a=x*10+u;b=y*10+v;ans=a-b;if(b===0)b=1+rnd(Math.max(1,u)),ans=a-b}}
  return{tag:"➕➖ 덧셈·뺄셈",q:a+" "+op+" "+b+" = ?",sub:"",opts:numOpts(ans,L==="s"?[1,2,3,10]:[1,10,2,20])}}
 if(k==="eng"){const m=rnd(6);
  if(m===3||m===4){const it=pickOne(PH);return{tag:"🔤 영어 회화",q:it[0],sub:"알맞은 대답은?",opts:txtOpts(it[2],it[3]),speak:it[0],small:true}}
  if(m===5){const it=pickOne(PH);return{tag:"🔤 영어 회화",q:it[0],sub:"무슨 뜻일까요?",opts:txtOpts(it[1],PH.filter(x=>x!==it).map(x=>x[1])),speak:it[0],small:true}}
  if(m===0){const it=pickOne(EN);return{tag:"🔤 영어",q:it[0],sub:"이건 영어로 뭘까요?",opts:txtOpts(it[1],EN.map(x=>x[1])),speak:it[1]}}
  if(m===1){const it=pickOne(EN);return{tag:"🔤 영어",q:it[1],sub:"우리말로 뭘까요?",opts:txtOpts(it[2],EN.map(x=>x[2])),speak:it[1]}}
  const it=pickOne(EN2);return{tag:"🔤 영어",q:it[0],sub:"우리말로 뭘까요?",opts:txtOpts(it[1],EN2.map(x=>x[1]).filter(x=>(/^\d+$/.test(x))===(/^\d+$/.test(it[1])))),speak:it[0]}}
 const g=pickOne(GEN);return{tag:"💡 상식",q:g[0],sub:"",opts:txtOpts(g[1],g[2]),small:true}}
